# Install Nginx on Ubuntu/Debian based runners
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Update package lists
      run: sudo apt-get update

    - name: Install Nginx
      run: sudo apt-get install -y nginx

