# Install Nginx on push
name: Install Nginx

on:
  push:
    branches: [ main ]  # Change "main" to your desired branch

jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Update package lists
      run: sudo apt-get update

    - name: Install Nginx
      run: sudo apt-get install -y nginx
